$fn = 48;

display_width = 220;
printable_width = 214;
body_height = 300;
body_depth = 55;
wall = 3;
corner_radius = 3;
camera_window = [36, 22];
panel_clearance = 0.4;
moving_clearance = 0.3;
tongue_clearance = 0.25;
tongue_overlap = 8;
m3_clearance = 3.4;
lean_angle = 7;
split_height = body_height / 2;
body_width = variant == "display" ? display_width : printable_width;

epsilon = 0.2;
rear_cover_thickness = 2.4;
rear_opening_margin = 14;
base_depth = 110;
base_height = 16;
panel_slot_depth = 4;
joint_lip = 1.8;
camera_adjustment = 10;
service_part_thickness = 3;
joint_fastener_x = [-75, -25, 25, 75];
rear_cover_fastener_x = [-90, 90];
rear_cover_fastener_z = [-58, 58];
rear_cover_boss_diameter = 12;
base_support_fastener_x = [-36, 36];
base_support_fastener_y = 20;
support_mount_offset_y = 8;
