#pragma once

#include "sdkconfig.h"

#define SG_PIN_UNASSIGNED (-1)

#define SG_PIN_CAMERA_I2C_SDA CONFIG_STROKEGUARD_CAMERA_I2C_SDA
#define SG_PIN_CAMERA_I2C_SCL CONFIG_STROKEGUARD_CAMERA_I2C_SCL

#define SG_PIN_NMO432_BCLK CONFIG_STROKEGUARD_NMO432_BCLK
#define SG_PIN_NMO432_WS   CONFIG_STROKEGUARD_NMO432_WS
#define SG_PIN_NMO432_DIN  CONFIG_STROKEGUARD_NMO432_DIN

#define SG_PIN_ST7789_MOSI   CONFIG_STROKEGUARD_PIN_ST7789_MOSI
#define SG_PIN_ST7789_SCLK   CONFIG_STROKEGUARD_PIN_ST7789_SCLK
#define SG_PIN_ST7789_CS     CONFIG_STROKEGUARD_PIN_ST7789_CS
#define SG_PIN_ST7789_DC     CONFIG_STROKEGUARD_PIN_ST7789_DC
#define SG_PIN_ST7789_RST    CONFIG_STROKEGUARD_PIN_ST7789_RST
#define SG_PIN_ST7789_BL     CONFIG_STROKEGUARD_PIN_ST7789_BL

#define SG_PIN_MAX98357_BCLK CONFIG_STROKEGUARD_PIN_MAX98357_BCLK
#define SG_PIN_MAX98357_LRC  CONFIG_STROKEGUARD_PIN_MAX98357_LRC
#define SG_PIN_MAX98357_DIN  CONFIG_STROKEGUARD_PIN_MAX98357_DIN

#define SG_PIN_ALERT_RGB     CONFIG_STROKEGUARD_PIN_ALERT_RGB
#define SG_PIN_ALERT_BUZZER  CONFIG_STROKEGUARD_PIN_ALERT_BUZZER
#define SG_PIN_BUTTON_1      CONFIG_STROKEGUARD_PIN_BUTTON_1
#define SG_PIN_BUTTON_2      CONFIG_STROKEGUARD_PIN_BUTTON_2
#define SG_PIN_BUTTON_3      CONFIG_STROKEGUARD_PIN_BUTTON_3
